# See default at https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.4

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 6

Layout/IndentationWidth:
  Width: 2

Naming/VariableName:
  EnforcedStyle: snake_case

Naming/FileName:
  Exclude:
    - 'lib/algosec-sdk.rb'

Layout/AlignParameters:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

#Style/EmptyLines:
#  Enabled: false
#
#Style/RescueModifier:
#  Enabled: false
#
#Style/EmptyLinesAroundBlockBody:
#  Enabled: false
#
#Style/EmptyLinesAroundClassBody:
#  Enabled: false
